### ISSUE TITLE
Move Request build() method inside .asObject/String() 

### ISSUE THREAD

**Issue by andyislegend** [corese4rch/cvurl#32]
**Problem**
Every time we create Request we call .build() method on RequestBuilder before actually executing it. 

**Solution**
Move that call inside of asString/Object() method would be more straightforward.

**Comment by yorekKap** [comment]
The purpose of .build method is reusability of requests. We can reuse the same builded request in many asObject() asString() methods calls.

**Comment by andyislegend** [comment]
We can have the same with RequestBuilder that is returned before .build(), isn't it?

**Comment by yorekKap** [comment]
not exactly cause in build() method the building of Java 11 HttpRequest is done, if that's overhead we can neglect then fine, let's drop it.

**Comment by andyislegend** [comment]
What type of overhead you're talking about?
